steps:
  # build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/website:$BUILD_ID', '.']
  # push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/website:$BUILD_ID']
  # Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'website', '--image', 'gcr.io/$PROJECT_ID/website:$BUILD_ID', '--region', 'us-central1','--platform', 'managed', '--quiet']
  # deploy to k8s cluster
- name: 'gcr.io/cloud-builders/kubectl'
  args: 
  - set
  - image
  - deployment
  - ds-web 
  - website-sha256=gcr.io/$PROJECT_ID/website:$BUILD_ID
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-east1-b'
  - 'CLOUDSDK_CONTAINER_CLUSTER=ds-k8s-private'
images:
- gcr.io/$PROJECT_ID/website
