steps:
  # build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/hacktheroofcicddemo:$BUILD_ID', '.']
  # push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/hacktheroofcicddemo:$BUILD_ID']
  # deploy to k8s cluster
- name: 'gcr.io/cloud-builders/gke-deploy:stable'
  args: ['run', '--image', 'gcr.io/$PROJECT_ID/hacktheroofcicddemo:$BUILD_ID', '-x', '80', '--location', 'us-east1-b', '--cluster', 'htr-gke']
- name: 'debian'
  args: ['echo', 'For questions, reach out to dslovin@google.com! Cheers!!']
